-- INSERT INTO ACCOUNT (ID, gender, name, NICKNAME, DESCRIPTION) VALUES ('1', '1', '1', '1', '1');
-- INSERT INTO ACCOUNT (ID, gender, name, NICKNAME, DESCRIPTION) VALUES ('2', '2', '2', '2', '2');
-- INSERT INTO ACCOUNT (ID, gender, name, NICKNAME, DESCRIPTION) VALUES ('3', '3', '3', '3', '3');

-- TRUNCATE TABLE PROFILE AND COMMIT
